# Generated by Django 4.2.20 on 2025-05-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iad_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.FloatField()),
                ('annual_income', models.FloatField()),
                ('num_bank_accounts', models.IntegerField()),
                ('num_credit_cards', models.IntegerField()),
                ('interest_rate', models.FloatField()),
                ('num_of_loans', models.IntegerField()),
                ('num_of_delayed_payments', models.IntegerField()),
                ('prediction', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
