# Generated by Django 4.2.20 on 2025-05-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iad_app', '0002_creditapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditapplication',
            name='name',
            field=models.CharField(default='Аноним', max_length=100),
            preserve_default=False,
        ),
    ]
