# Generated by Django 4.2.20 on 2025-05-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iad_app', '0004_delete_creditapplication_analysisresult_credit_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='credit_score',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='predicted_score',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='suggested_rate',
            field=models.FloatField(),
        ),
    ]
